create table user
( ID integer auto_increment ,
constraint const1 primary key (ID),
username Varchar  (50) ,
address Varchar  (50) ,
age Integer )ENGINE=InnoDB DEFAULT CHARSET=utf8

create table user2
( ID integer auto_increment ,
constraint const1 primary key (ID),
username2 Varchar  (50) ,
address2 Varchar  (50) ,
age2 Integer )ENGINE=InnoDB DEFAULT CHARSET=utf8

create table user3
( ID integer auto_increment ,
constraint const1 primary key (ID),
username3 Varchar  (50) ,
address3 Varchar  (50) ,
age3 Integer )ENGINE=InnoDB DEFAULT CHARSET=utf8