CREATE TABLE USERS
(ID INTEGER,
CONSTRAINT CONST1 PRIMARY KEY (ID),
USERNAME VARCHAR (50) ,
PHONENUMBER VARCHAR (50) ,
ADDRESS VARCHAR (50) ,
ALIVE INTEGER, 
AGE INTEGER);

CREATE TABLE USERS2
(ID INTEGER,
CONSTRAINT CONST2 PRIMARY KEY (ID),
USERNAME VARCHAR (50) ,
PHONENUMBER VARCHAR (50) ,
ADDRESS VARCHAR (50) ,
ALIVE INTEGER, 
AGE INTEGER);